/* eslint-disable @next/next/no-img-element */
"use client";

import React from "react";
import { FiImage, FiUpload, FiSave, FiRefreshCw } from "react-icons/fi";
import { useEffect, useState } from "react";
import { useCustomPageHooks } from "@/hooks/admin/useCustomPageHooks";

export default function AddPhotoGallery() {
  const { onSubmit, register, isLoading, errors, setSlugTouched, setMetaTouched } =
    useCustomPageHooks();


  return (
    <div className="admin-page">
      <div className="admin-card">
        {/* Header */}
        <div className="admin-card-header">
          <div className="admin-card-title-wrap">
            <FiImage size={18} />
            <h5 className="admin-card-title">Create New Page</h5>
          </div>
        </div>

        <div className="admin-card-body">
          <form onSubmit={onSubmit} encType="multipart/form-data">
            <div className="row">
              
              <div className="col-md-4 mb-3">
                <label className="form-label fw-semibold">
                  Page Name
                </label>
                <input
                  type="text"
                  className={`form-control ${errors.page_name ? "is-invalid" : ""}`}
                  placeholder="Enter page name"
                  {...register("page_name", {
                    required: "Page Name is required",
                  })}
                />
                {errors.page_name && (
                  <div className="invalid-feedback">{errors.page_name.message}</div>
                )}
              </div>
              <div className="col-md-4 mb-3">
                <label className="form-label fw-semibold">
                  Page Slug (URL)
                </label>
                <input
                  type="text"
                  className={`form-control ${errors.page_slug ? "is-invalid" : ""}`}
                  placeholder="Page Slug (autogenerated)"
                  {...register("page_slug", {
                    required: "Page slug is required",
                    onChange: () => setSlugTouched(true),
                  })}
                />
                {errors.page_slug && (
                  <div className="invalid-feedback">{errors.page_slug.message}</div>
                )}
              </div>
              <div className="col-md-4 mb-3">
                <label className="form-label fw-semibold">
                  Meta Title
                </label>
                <input
                  type="text"
                  className={`form-control ${errors.meta_title ? "is-invalid" : ""}`}
                  placeholder="Page Title (autogenerated)"
                  {...register("meta_title", {
                    required: "Meta title is required",
                    onChange: () => setMetaTouched(true),
                  })}
                />
                {errors.meta_title && (
                  <div className="invalid-feedback">{errors.meta_title.message}</div>
                )}
              </div>
              <div className="col-md-6 mb-3">
                <label className="form-label fw-semibold">
                  Meta Keywords
                </label>
                <textarea
                  className={`form-control ${errors.meta_keyword ? "is-invalid" : ""}`}
                  placeholder="eg. keyword1, keyword2, keyword3"
                  {...register("meta_keyword")}
                ></textarea>
                {errors.meta_keyword && (
                  <div className="invalid-feedback">{errors.meta_keyword.message}</div>
                )}
              </div>
              <div className="col-md-6 mb-3">
                <label className="form-label fw-semibold">
                  Meta Description
                </label>
                <textarea
                  className={`form-control ${errors.meta_description ? "is-invalid" : ""}`}
                  placeholder="Write page description here"
                  {...register("meta_description")}
                ></textarea>
                {errors.meta_description && (
                  <div className="invalid-feedback">{errors.meta_description.message}</div>
                )}
              </div>
              <div className="col-md-12 mb-3">
                <label className="form-label fw-semibold">
                  SEO JS Scripts for Page (optional)
                </label>
                <textarea
                  className={`form-control ${errors.js_scripts ? "is-invalid" : ""}`}
                  placeholder="Page javascripts eg. gtag.js, fb-sjak263286.js"
                  {...register("js_scripts")}
                  rows={5}
                ></textarea>
                {errors.js_scripts && (
                  <div className="invalid-feedback">{errors.js_scripts.message}</div>
                )}
              </div>
              

            </div>
            

            {/* Actions */}
            <div className="admin-form-actions">
              <button
                type="submit"
                className="theme-btn"
                disabled={isLoading}
              >
                <FiSave />
                {isLoading ? "Saving..." : "Save"}
              </button>

              <button type="reset" className="theme-btn btn-danger">
                <FiRefreshCw />
                Reset
              </button>
            </div>
          </form>
        </div>

      </div>
    </div>
  );
}
